-- CreateTable
CREATE TABLE "accounts" (
    "id" TEXT,
    "_platform" TEXT,
    "username" TEXT,
    "full_name" TEXT,
    "description" TEXT,
    "created_time" TIMESTAMP(3),
    "lang" TEXT[],
    "followers_count" INTEGER,
    "is_verified" BOOLEAN,
    "restricted" TEXT[],
    "_added_at" TIMESTAMP(3),
    "_updated_at" TIMESTAMP(3),
    "_id" INTEGER NOT NULL,
    "_status" TEXT,
    "_status_details" JSONB,
    "_active" BOOLEAN,
    "_source_id" INTEGER,
    "id_alt" TEXT,
    "posts_count" INTEGER,
    "jenkins_build_number" INTEGER,
    "jenkins_job_name" TEXT,

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("_id")
);

-- CreateTable
CREATE TABLE "posts" (
    "internalID" SERIAL NOT NULL,
    "character" TEXT,
    "_platform" TEXT,
    "original_post_author_id" TEXT,
    "created_time" TIMESTAMP(3),
    "type" TEXT,
    "links" TEXT[],
    "domains" TEXT[],
    "text_original" TEXT,
    "lang" TEXT,
    "likes_count" INTEGER,
    "shares_count" INTEGER,
    "comments_count" INTEGER,
    "views_count" INTEGER,
    "toxicity" DOUBLE PRECISION,
    "severe_toxicity" DOUBLE PRECISION,
    "threat" DOUBLE PRECISION,
    "identity_attack" DOUBLE PRECISION,
    "insult" DOUBLE PRECISION,
    "profanity" DOUBLE PRECISION,
    "restricted" TEXT[],
    "_added_at" TIMESTAMP(3),
    "_updated_at" TIMESTAMP(3),
    "engagement" INTEGER,
    "engagement_identified" INTEGER,
    "nf_engagement_n" INTEGER,
    "nf_engagement_p" DOUBLE PRECISION,
    "engagers_unique" TEXT[],
    "engagers_unique_n" INTEGER,
    "engagers_unique_p" DOUBLE PRECISION,
    "nf_unique_engagement_n" INTEGER,
    "_id" INTEGER,
    "_account_id" INTEGER,
    "_replied_to_id" TEXT,
    "_text_additional" TEXT,
    "_status" TEXT,
    "_status_details" JSONB,
    "_active" BOOLEAN,
    "_original_post_id" TEXT,
    "_post_platform_id_new" TEXT,
    "_follower_engagement_n" INTEGER,
    "_follower_engagers_unique_n" INTEGER,
    "account_id" TEXT,
    "_jenkins_build_number" INTEGER,
    "_jenkins_job_name" TEXT,
    "_perspective" BOOLEAN,

    CONSTRAINT "posts_pkey" PRIMARY KEY ("internalID")
);

-- CreateTable
CREATE TABLE "sources" (
    "_id" SERIAL NOT NULL,
    "platform_id" TEXT,
    "platform_username" TEXT,
    "owner_name" TEXT,
    "_platform" TEXT,
    "url" TEXT,
    "languages" TEXT[],
    "verified" BOOLEAN,
    "edge_case" BOOLEAN,
    "labelled" BOOLEAN,
    "availability" TEXT,
    "n_posts" INTEGER,
    "likes_median" INTEGER,
    "shares_median" INTEGER,
    "comments_median" INTEGER,
    "date_first" TIMESTAMP(3),
    "date_last" TIMESTAMP(3),
    "engagement_median" DOUBLE PRECISION,
    "outlinks_percentage" DOUBLE PRECISION,
    "outlink_top" TEXT,
    "perspective_n" INTEGER,
    "severe_toxicity_n" INTEGER,
    "identity_attack_n" INTEGER,
    "threat_n" INTEGER,
    "severe_toxicity_p" DOUBLE PRECISION,
    "identity_attack_p" DOUBLE PRECISION,
    "threat_p" DOUBLE PRECISION,
    "toxic_likes_median" INTEGER,
    "toxic_shares_median" INTEGER,
    "toxic_comments_median" INTEGER,
    "toxic_engagement_median" INTEGER,
    "subscribers_start" INTEGER,
    "subscribers_end" INTEGER,
    "subscriber_growth_n" INTEGER,
    "subscriber_growth_p" DOUBLE PRECISION,
    "exposure_n" INTEGER,
    "exposure_median" INTEGER,
    "toxic_exposure" INTEGER,
    "toxic_n" INTEGER,
    "_added_at" TIMESTAMP(3),
    "_updated_at" TIMESTAMP(3),
    "subscribers_start_date" TIMESTAMP(3),
    "subscribers_end_date" TIMESTAMP(3),

    CONSTRAINT "sources_pkey" PRIMARY KEY ("_id")
);
